### ISSUE TITLE
Double check Location info

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#150]
In `www/config.yml`, chapter info may not be correct.  There are in fact a handful of incorrect Meetup IDs.  I'd like to:
1. Double check meetup IDs
2. Add locations that are missing (cross reference a list that I have)
3. Double check other links to other media, etc for correctness
4. For "retired" or "inactive" locations, create a new item in the `config.yml` file named `inactive_chapters` with all the same info as `chapters`:

``` yaml
chapters:
    - foo
    - bar
inactive_chapters:
    - baz
```
